# Generated by Django 5.0.6 on 2024-06-22 13:51

import downloader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=downloader.models.image_upload_path),
        ),
    ]
